services:
  ui:
    container_name: app_ui
    build:
      context: ./
      dockerfile: ./docker/ui/Dockerfile
    volumes:
        - ./ui/:/usr/src/app
        - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:5174'

  app:
    container_name: app_api
    build: ./docker/api/php
    volumes:
      - ./api:/var/api

  nginx:
    image: nginx
    container_name: app_www
    ports:
      - 8000:80
    volumes:
      - ./api:/var/api
      - ./docker/api/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/api
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: app_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./api/mysql/data:/var/lib/mysql
      - ./docker/api/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/api/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: app_phpmyadmin
      ports:
          - 8080:80
      environment:
          PMA_USER: "db-user"
          PMA_PASSWORD: "db-pass"
          PMA_HOST: "db"
      depends_on:
          - db
