version: "3.7"
services:
  db:
    image: mysql:8.0
    container_name: wp_mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: adkjoneainr2 # rootユーザのパスワード
      MYSQL_DATABASE: db_local # WordPress用データベース名
      MYSQL_USER: wp_user # WordPress用データベース接続ユーザ名
      MYSQL_PASSWORD: adkjoneainr1 # WordPress用データベース接続パスワード

  php:
    build:
      context: ./docker/php/7.4
      dockerfile: Dockerfile
    container_name: wp_www
    volumes:
      - ./htdocs:/var/www/html
    links:
      - db
    depends_on:
      - db
    ports:
      - 8000:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
